(deftheme hello
  "Created 2020-03-09.")

(custom-theme-set-faces
 'hello
 '(default ((t (:family "default" :foundry "default" :width normal :height 1 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#ddd" :background "#444444" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#ffffff" :background "#ffffff"))))
 '(line-number ((t (:foreground "#555"))))
 '(line-number-current-line ((t (:foreground "#666" :background "#333"))))
 '(vertical-border ((t (:foreground "#444" :background "#444"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#ffffff"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#eee"))))
 '(highlight ((t (:background "#333"))))
 '(region ((t (:foreground "#444444" :background "#EEEEEE"))))
 '(shadow ((t (:foreground "#888888"))))
 '(secondary-selection ((t (:background "#444444"))))
 '(trailing-whitespace ((t (:background "#FFFFFF"))))
 '(font-lock-builtin-face ((t (:foreground "#888"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#000" :weight bold :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#ffdcbd"))))
 '(font-lock-doc-face ((t (:foreground "#CCCCCC"))))
 '(font-lock-function-name-face ((t (:foreground "#fff"))))
 ;; '(font-lock-function-name-face ((t (:weight bold :foreground "#fff"))))
 '(font-lock-variable-name-face ((t (:foreground "#fff"))))
 '(nxml-element-local-name ((t (:foreground "#999"))))
 '(nxml-tag-delimiter ((t (:foreground "#777"))))
 '(web-mode-html-tag-bracket-face ((t (:foreground "#777"))))
 '(nxml-text ((t (:foreground "#fff"))))
 '(js2-object-property ((t (:slant italic :foreground "#FFFFFF"))))
 '(js2-function-param ((t (:foreground "#FFFFFF"))))
 '(font-lock-keyword-face ((t (:foreground "#888"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#ffffff"))))
 '(font-lock-preprocessor-face ((t (:foreground "#ffffff"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#EEEEEE"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#ffffff"))))
 '(font-lock-string-face ((t (:foreground "#b4d9b8"))))
 ;; '(font-lock-type-face ((t (:underline (:color foreground-color :style line) :foreground "#FFFFFF"))))
 '(font-lock-type-face ((t (:foreground "#eee"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "gold"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#ffffff"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#ffffff"))))
 '(fringe ((t (:foreground "#AAAAAA" :background "#666666"))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box nil :foreground "#444444" :background "#EEEEEE"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#444444"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#444444" :background "#AAAAAA"))))
 '(isearch ((t (:foreground "#000000" :background "yellow"))))
 '(isearch-fail ((t (:foreground "#ffffff" :background "#AAAAAA"))))
 '(lazy-highlight ((t (:weight bold :foreground "#ffffff" :background "#666666"))))
 '(flycheck-warning-overlay ((t (:foreground "#ffffff" :background "yellow"))))
 '(flycheck-info-overlay ((t (:underline "green"))))
 '(flycheck-info ((t (:underline "green"))))
 '(flycheck-warning ((t (:foreground "#ffffff" :background "yellow"))))
 '(flycheck-error ((t (:foreground "#ffffff" :background "red"))))
 '(match ((t (:weight bold :foreground "#ffffff" :background "#444444"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'hello)
